

#define _FILE_FAILURE 29
#define _FILE_NOT_EXIST 30
#define _FILE_TOO_BIG 31
#define _BAD_AUTHFILE_FORMAT 32

#define _BAD_USERNAME_OR_PASS 48
#define _REPLAY_BAD 49
#define _CONNECTION_CLOSED 50
#define _CONNECTION_FAILED 51
#define _CONNECTION_FAILED_TO_OPEN 52
#define _BAD_CERTFILE 53
